/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'legen' at '9/11/18 12:28 PM' with Gradle 2.14.1
 *
 * @author legen, @date 9/11/18 12:28 PM
 */
public class Library {
	public static void main(String arg[]){
		Library lib = new Library();
		if (lib.someLibraryMethod())
			System.out.println("When there is a fire, comit and push");
			System.out.println();
	}
    public boolean someLibraryMethod() {
        return true;
    }
}
